services:
  tg-postgres:
    image: postgres
    restart: always
    container_name: tg-postgres
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - internal-backend-network

  tg-service:
    build:
      context: .
    container_name: tg-service
    expose:
      - ${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      - tg-postgres
    networks:
      - internal-backend-network

networks:
  internal-backend-network:
    external: true
