version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql+psycopg2://user:password@db:5432/user_service

volumes:
  db-data:

