services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_NAME} -d ${POSTGRES_USER_DATABASE_NAME}"]
      interval: 1ms
      retries: 10000
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
